### ISSUE TITLE
tensorflow-gpu install

### ISSUE THREAD

**Issue by cloudwinders** [pmcheng/rsna-pneumonia#1]
Hi, 
I just realized in your file: requirements.txt, requires tensorflow==1.9.0 (tensorflow for cpu usage only) for the system environment.
But I look through your code, that I found gpu setting is enabled for training stage.
Thus, do you need to clarify that in the requirements.txt file, tensorflow-gpu==1.9.0 should be installed?

**Comment by pmcheng** [comment]
Thanks, you are correct.  I changed the requirements.txt file.
