### ISSUE TITLE
How to use the repo for multi-class detection task

### ISSUE THREAD

**Issue by akhanss** [pmcheng/rsna-pneumonia#2]
Thanks for sharing this great repo. I saw you didn't utilize labels output during prediction since it contains only one class. However,  I am just wondering whether we can use this repo for a multi-class detection task. If yes, how to do that?

Best,
Azam.

**Comment by pmcheng** [comment]
Hi Azam,

If you're interested in multi-class detection, you should probably start directly from [keras-retinanet](https://github.com/fizyr/keras-retinanet), from which this project is derived.  The very slight modifications I made to keras-retinanet are documented in the fork [here](https://github.com/pmcheng/keras-retinanet), but those modifications may not be at all relevant to what you're interested in doing.

Phil
