### ISSUE TITLE
Getting low score on private LB

### ISSUE THREAD

**Issue by SurajK7** [pmcheng/rsna-pneumonia#3]
Hi, thank you for sharing this wonderful repo.
I tried following the steps as mentioned in the repo to reproduce the results.
But the score I am getting on private LB is around 0.18.
Am I missing something?
Any help would be greatly appreciated.

**Comment by pmcheng** [comment]
Are you using the trained .h5 files, or are you training the networks?  If you are training, the results are not deterministic.

**Comment by SurajK7** [comment]
Thank you for your response. I used the trained .h5 files.

**Comment by pmcheng** [comment]
Please compare your output to the attached csv file.

[stage2_test.zip](https://github.com/pmcheng/rsna-pneumonia/files/4677406/stage2_test.zip)

**Comment by SurajK7** [comment]
Thank you for providing with the CSV file. It seems there is something wrong with Kaggle as the outputs are identical. Thank you again for your time and effort.

**Comment by Sum-nuts** [comment]
Hello,　why is the Score predictive value greater than 1?
Let me know, thank you
